replace-table-gui: true # Replaces enchantment table GUI with a custom one.
replace-anvil-gui: true # Replaces the default anvil GUI with a custom one.
fireworks-on-enchants: true # Launches a firework on every successful enchant. Note that these fireworks are harmful!

bStats: true # A boolean indicating about bStats job. Collects default bStats data and the used language.
updater: 24 # Each X hours, an updater checks for updates. Default: 24.

activated: true # A boolean, indicating whether a message should be sent upon enchantment activation.

permitScrolls: true # A boolean indicating whether to enable scrolls or not.

lang: en # Selected from below.

# This section contains the used UnderscoreEnchants.messages.
# They are translated to English and Russian by default, but in case you want to add your own translation,
# you can create your own section and translate the messages, then put the section name in the "lang" section.
# Also, if you have translated a section, it'd be neat if you made a pull request :)
# It helps out other foreign users, and you'll be credited in the update.
# P.S. The single quotation mark ( ' ) must be written twice (in words like can't, doesn't -> can''t, doesn''t)
messages:
  en:
    no-perms: '&cInsufficient permissions!' # Called when a command was executed with a player without proper permissions.
    no-console: '&cYou can''t use this from console!' # Called when a command was executed from console, though wasn't supposed to.
    creating-log: '&bCreating a log...' # Called when a /log command is used.
    log-created: '&6A log has been created in &b/plugins/UnderscoreEnchants/logfile.log/ folder.' # Called when log creation is finished.
    couldnt-make-log: '&cCouldn''t create a log!' # Called when something went wrong while creating a log.
    improper-args: '&cImproper amount of arguments!' # Called when improper amount of arguments are inputted in the command.
    wrong-enchantment-name: '&cCouldn''t enchant the item - unknown enchantment!' # Called when /uenchant command has a wrong enchantment argument.
    wrong-enchantment-level: '&cCouldn''t enchant the item - its level is either higher than the maximum or less than 1!' # Called when /uenchant command has a wrong level argument.
    enchanted: '&6Enchanted your item with &b%name% %level%.' # Called after a successful /uenchant.
    activated: '&6You have activated the &l&b%name% enchantment.' # Called when an enchantment was activated. P.S. "activated" boolean (at the top) must be true for this.
    no-bleed: '&eYou are no longer bleeding.' # Called when a player stops bleeding from Spade.
    # Credit to ZBLL (the creator)

  ru:
    no-perms: '&cНедостаточно прав!'
    no-console: '&сВы не можете использовать это из консоли!'
    creating-log: '&bСоздаю лог...'
    log-created: '&6Лог был создан в папке &b/plugins/UnderscoreEnchants/logfile.log/.'
    couldnt-make-log: '&cНе получилось создать лог!'
    improper-args: '&cНеверное количество аргументов!'
    wrong-enchantment-name: '&cНе получилось зачаровать предмет - неизвестное зачарование!'
    wrong-enchantment-level: '&cНе получилось зачаровать предмет - уровень либо превышает максимум, либо меньше чем 1!'
    enchanted: '&6Ваш предмет был зачарован на &b%name% %level%.'
    activated: '&6Вы использовали зачарование &l&b%name%.'
    no-bleed: '&eВы больше не истекаете кровью.'
    # Credit to ZBLL (the creator)

  ro:
    no-perms: '&cPermisiuni insuficiente!'
    no-console: '&cNu poți folosi asta din consolă!'
    creating-log: '&bCrearea unui jurnal...'
    log-created: '&6Un jurnal a fost creat în folderul &b/plugins/UndercoreEnchants/logfile.log/.'
    couldnt-make-log: '&cNu s-a putut crea un jurnal!'
    improper-args: '&cNumăr nepotrivit de argumente!'
    wrong-enchantment-name: '&cNu s-a putut încânta obiectul - vrajeală necunoscută!'
    wrong-enchantment-level: '&cNu s-a putut vrăji elementul - nivelul său este fie mai mare decât maxim, fie mai mic de 1!'
    enchanted: '&6V-ați vrăjit articolul cu &b%name% %level%.'
    activated: '&6Ai activat vraja &l&b%name%.'
    no-bleed: '&eNu mai sângerezi.'
    # Credit to Lukedy

  it:
    no-perms: '&cPermessi insufficienti!'
    no-console: '&cNon si può usare da console!'
    creating-log: '&bCreare un log...'
    log-created: '&6Un log è stato creato nella cartella &b/plugins/UnderscoreEnchants/logfile.log/.'
    couldnt-make-log: '&cImpossibile creare un log!'
    improper-args: '&cQuantità impropria di parametri!'
    wrong-enchantment-name: '&cImpossibile incantare l''oggetto - incanto sconosciuto!'
    wrong-enchantment-level: '&cImpossibile incantare l''oggetto - il suo livello è superiore al massimo o inferiore a 1!'
    enchanted: '&6Incanta il tuo oggetto con &b%name% %level%.'
    activated: '&6Hai attivato l'incanto &l&b%name%.'
    no-bleed: '&eNon stai più sanguinando.'
    # Credit to DeepL (the translation might not be 100% accurate, feel free to edit!)

  es:
    no-perms: '&c¡Permisos insuficientes!'
    no-console: '&c¡No se puede utilizar desde una consola!'
    creating-log: '&bCreando un registro...'
    log-created: '&6Se ha creado un registro en la carpeta &b/plugins/UnderscoreEnchants/logfile.log/.'
    couldnt-make-log: '¡No se pudo crear un registro!'
    improper-args: '&c¡Cantidad inadecuada de parámetros!'
    wrong-enchantment-name: '&cNo se ha podido encantar el objeto - ¡encantamiento desconocido!'
    wrong-enchantment-level: '&cNo se ha podido encantar el objeto - ¡su nivel es superior al máximo o inferior a 1!'
    enchanted: '&6Enchanted su artículo con &b%name% %level%.'
    activated: '&6Has activado el encantamiento &l&b%name%.'
    no-bleed: '&eYa no estás sangrando.'
    # Credit to DeepL (the translation might not be 100% accurate, feel free to edit!)

  de:
    no-perms: '&cKeine Berechtigung!'
    no-console: '&cDu kannst diesen Befehl nicht von der Konsole benutzen!'
    creating-log: '&bErstelle Log...'
    log-created: '&6Log wurde im Ordner &b/plugins/UnderscoreEnchants/logfile.log/ erstellt.'
    couldnt-make-log: '&cKonnte kein Log erstellen!'
    improper-args: '&cUngültige Anzahl an Parametern!'
    wrong-enchantment-name: '&cKonnte den Gegenstand nicht verzaubern - unbekannte Verzauberung!'
    wrong-enchantment-level: '&cKonnte den Gegenstand nicht verzaubern - das angegebene Level ist entweder höher als das Maximum oder kleiner als 1!'
    enchanted: '&6Dein Gegenstand wurde mit &b%Name% %level% verzaubert.'
    activated: '&6Du hast die Verzauberung &l&b%name% aktiviert.'
    no-bleed: '&eDu blutest nicht mehr.'

  fr:
    no-perms: '&cPermissions insuffisantes!'
    no-console: '&cVous ne pouvez pas l''utiliser depuis la console!'
    creating-log: '&bCréation d''un journal...'
    log-created: '&6Un journal a été créé dans le dossier &b/plugins/UnderscoreEnchants/logfile.log/'.
    couldnt-make-log: '&cImpossible de créer un journal!'
    improper-args: '&cQuantité incorrecte de paramètres!'
    wrong-enchantment-name: '&cPeut pas enchanter l''objet - enchantement inconnu!'
    wrong-enchantment-level: '&cPas pu enchanter l''objet - son niveau est soit supérieur au maximum, soit inférieur à 1!'
    enchanted: '&6Enchanter votre objet avec &b%name% %level%.'
    activated: '&6Vous avez activé l''enchantement &l&b%name%.'
    no-bleed: '&eVous ne saignez plus.'
    # Credit to DeepL (the translation might not be 100% accurate, feel free to edit!)

  tr:
    no-perms: '&cYetersiz izinler!'
    no-console: '&cBunu konsoldan kullanamazsınız!'
    creating-log: '&bBir günlük oluşturuluyor...'
    log-created: '&b/plugins/UnderscoreEnchants/logfile.log/ klasöründe &6bir günlük oluşturuldu.'
    couldnt-make-log: '&cGünlük oluşturulamadı!'
    improper-args: '&cUygunsuz sayıda argüman!'
    wrong-enchantment-name: '&cÖğeyi büyüleyemedi - bilinmeyen büyü!'
    wrong-enchantment-level: '&cÖğeyi büyüleyemedi - seviyesi ya maksimumdan yüksek ya da 1''den az!'
    enchanted: '&6Öğenizi &b%name% %level% ile büyüledi.'
    activated: '&6&l&b%name% büyüsünü etkinleştirdiniz.'
    no-bleed: '&eArtık kanamanız yok.'
    # Credit to Kigo


armor:
  - '&7' # Leave this line as it is now, please.
  - '&5Armor Enchantments'
  - '&7 '
bows:
  - '&7'
  - '&5Bow Enchantments'
  - '&7 '
tools:
  - '&7'
  - '&5Tool Enchantments'
  - '&7 '
tridents:
  - '&7'
  - '&5Trident Enchantments'
  - '&7 '
weapons:
  - '&7'
  - '&5Weapon Enchantments'
  - '&7 '

version: '1.9' # DO NOT CHANGE THIS YOURSELF!!!
