# Thanks for purchasing!
# P.S. Please do not change the language AFTER the plugin has been used for a while - the enchantment names will be bugged!
replace-table-gui: true # Replaces enchantment table GUI with a custom one.
replace-anvil-gui: true # Replaces the default anvil GUI with a custom one.
fireworks-on-enchants: true # Launches a firework on every successful enchant. Note that these fireworks are harmful!

lang: en # Selected from below.

bStats: true # A boolean indicating about bStats job. Collects default bStats data and the used language.
updater: 24 # Each X hours, an updater checks for updates. Default: 24.

activated: true # A boolean, indicating whether a message should be sent upon enchantment activation.

# This section contains the used messages.
# They are translated to English and Russian by default, but in case you want to add your own translation,
# you can create your own section and translate the messages, then put the section name in the "lang" section.
# Also, if you have translated a section, it'd be neat if you made a pull request :)
# It helps out other foreign users, and you'll be credited in the update.
# P.S. The single quotation mark ( ' ) must be written twice (in words like can't, doesn't -> can''t, doesn''t)
messages:
  en:
    no-perms: '&cInsufficient permissions!' # Called when a command was executed with a player without proper permissions.
    no-console: '&cYou can''t use this from console!' # Called when a command was executed from console, though wasn't supposed to.
    creating-log: '&bCreating a log...' # Called when a /log command is used.
    log-created: '&6A log has been created in &b/plugins/UnderscoreEnchants/logfile.log/ folder.' # Called when log creation is finished.
    couldnt-make-log: '&cCouldn''t create a log!' # Called when something went wrong while creating a log.
    improper-args: '&cImproper amount of arguments!' # Called when improper amount of arguments are inputted in the command.
    wrong-enchantment-name: '&cCouldn''t enchant the item - unknown enchantment!' # Called when /uenchant command has a wrong enchantment argument.
    wrong-enchantment-level: '&cCouldn''t enchant the item - its level is either higher than the maximum or less than 1!' # Called when /uenchant command has a wrong level argument.
    enchanted: '&6Enchanted your item with &b%name% %level%.' # Called after a successful /uenchant.
    activated: '&6You have activated the &l&b%name% enchantment.' # Called when an enchantment was activated. P.S. "activated" boolean (at the top) must be true for this.
    no-bleed: '&eYou are no longer bleeding.' # Called when a player stops bleeding from Spade.

  ru:
    no-perms: '&cНедостаточно прав!'
    no-console: '&сВы не можете использовать это из консоли!'
    creating-log: '&bСоздаю лог...'
    log-created: '&6Лог был создан в папке &b/plugins/UnderscoreEnchants/logfile.log/.'
    couldnt-make-log: '&cНе получилось создать лог!'
    improper-args: '&cНеверное количество аргументов!'
    wrong-enchantment-name: '&cНе получилось зачаровать предмет - неизвестное зачарование!'
    wrong-enchantment-level: '&cНе получилось зачаровать предмет - уровень либо превышает максимум, либо меньше чем 1!'
    enchanted: '&6Ваш предмет был зачарован на &b%name% %level%.'
    activated: '&6Вы использовали зачарование &l&b%name%.'
    no-bleed: '&eВы больше не истекаете кровью.'

armor:
  - '&7' # Leave this line as it is now, please.
  - '&5Armor Enchantments'
  - '&7 '
bows:
  - '&7'
  - '&5Bow Enchantments'
  - '&7 '
tools:
  - '&7'
  - '&5Tool Enchantments'
  - '&7 '
tridents:
  - '&7'
  - '&5Trident Enchantments'
  - '&7 '
weapons:
  - '&7'
  - '&5Weapon Enchantments'
  - '&7 '

version: '1.5' # DO NOT CHANGE THIS YOURSELF!!!
